[package]
name = "rustpy"
version = "0.1.0"
edition = "2021"

[dependencies]
rustpy-macros = { path = "../rustpy-macros" }
rustpy-dylib = { path = "../rustpy-dylib" }

libloading = "0.8.1"
cpython = {version = "0.7.1"}
lazy_static = "1.4.0"


