[package]
name = "rustpy-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.35"
syn = {version = "2.0.48", features = ["full"]}
proc-macro2 = "1.0"

[lib]
crate-type = ["proc-macro"]
proc-macro = true
